services:
    kasimi.loginrequired.listener:
        class: kasimi\loginrequired\event\listener
        arguments:
            - '@user'
            - '@config'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
