services:
  phpbb:
    build:
      context: .
    #image: bitnami/phpbb:3.3.0
    ports:
      - "8088:80"
    env_file:
      - docker/env
   # volumes:
     #  - ./Docker/volume:/update
    networks:
        - infratool     
networks:
    infratool:
      external: true