services:
  phpbb:
    # build:
    #   context: .
    image: latheefp/itrunbook:3.3
    ports:
      - "8088:80"
    env_file:
      - docker/env
    volumes:
     #  - ./phpBB-3.3:/var/www/html
       - attachment:/var/www/html/files
    networks:
        - infratool     
networks:
    infratool:
      external: true
volumes:
  attachment: