# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itrunbook.fullname" . }}-secret
  labels:
    app: {{ include "itrunbook.fullname" . }}
type: Opaque
data:

  DB_HOST: {{ .Values.secrets.DB_HOST | b64enc | quote }}
  DB_NAME: {{ .Values.secrets.DB_NAME | b64enc | quote }}
  DB_USER: {{ .Values.secrets.DB_USER | b64enc | quote }}
  DB_PASS: {{ .Values.secrets.DB_PASS | b64enc | quote }}
