name: Build image , push repository and run on k8s
on:
  push:
    branches:
      - main  # Change this to your main branch
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Build and push Docker image
      env:
        
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        APP_NAME: ${{ github.event.repository.name }}
        VERSION: ${{ vars.VERSION }}
      run: |
        echo "Building image with tag $VERSION"
        # docker build . -t latheefp/$APP_NAME:$VERSION \
        #   --build-arg BUILD_DATE=${CURRENT_DATE} \
        #   --build-arg COMMIT_HASH=${COMMIT_HASH}
        echo "pass is $DOCKERHUB_PASSWORD" >>tmp1
        echo "user is $DOCKERHUB_USERNAME" >>tmp1
        ls -ltra 
        echo "typging file"
        cat tmp1
        echo "running docker login"
        
        docker tag latheefp/$APP_NAME:$VERSION latheefp/$APP_NAME:latest
        docker push latheefp/$APP_NAME:latest
        docker push latheefp/$APP_NAME:$VERSION


    # - name: Update Kubernetes deployment
    #   env:
    #     CURRENT_DATE: $(date +"%Y%m%d%H%M%S")
    #     COMMIT_HASH: $(git rev-parse --short HEAD)
    #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        
    #   run: |
    #     CURRENT_DATE=$(date +"%Y%m%d")
    #     COMMIT_HASH=$(git rev-parse --short HEAD)
    #     IMAGE_TAG=${CURRENT_DATE}_${COMMIT_HASH}  
    #     echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig.yaml
    #     echo image tag is $IMAGE_TAG
    #     export KUBECONFIG=$PWD/kubeconfig.yaml  # Set KUBECONFIG to the path of the kubeconfig file
    #     kubectl config get-contexts  # Lists available contexts
    #     kubectl config use-context egrand
    #     kubectl set image -n  wapi  deployment/wajunction wapi=latheefp/wapi:$IMAGE_TAG
    #     kubectl -n wapi rollout restart deployment/wajunction
